name: pro_map
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
 sdk: '>=3.4.0 <4.0.0'
dependencies:
 flutter:
   sdk: flutter
 cupertino_icons: ^1.0.6
 yandex_mapkit: ^4.0.2
 latlong2: ^0.9.0
 geolocator: ^11.1.0


dev_dependencies:
 flutter_test:
   sdk: flutter
 flutter_lints: ^3.0.0


flutter:
 uses-material-design: true
 assets:
  - assets/images/